#!/usr/bin/env bash
# Run the Episodic Perception demo in Webots.
#
#   ./scripts/run_webots_demo.sh                     GUI, ground-truth detector
#   ./scripts/run_webots_demo.sh --detector ssd      GUI, real SSD-MobileNet-V2
#   ./scripts/run_webots_demo.sh --headless          no X server (CI / servers)
#   ./scripts/run_webots_demo.sh --record out.mp4    headless + record a video
#
# Start the dashboard first so the run has somewhere to stream to:
#   python -m demo.run_demo --no-sim
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
WORLD="$REPO/webots/worlds/episodic_lab.wbt"

HEADLESS=0
RECORD=""
CONTROLLER_ARGS=()

while [ $# -gt 0 ]; do
  case "$1" in
    --headless) HEADLESS=1; shift ;;
    --record)   HEADLESS=1; RECORD="${2:?--record needs an output .mp4 path}"; shift 2 ;;
    --detector) CONTROLLER_ARGS+=(--detector "${2:?--detector needs recognition|ssd}"); shift 2 ;;
    --fog-url)  CONTROLLER_ARGS+=(--fog-url "$2"); shift 2 ;;
    *)          CONTROLLER_ARGS+=("$1"); shift ;;
  esac
done

if ! command -v webots >/dev/null 2>&1; then
  echo "webots is not on PATH. Install it from https://cyberbotics.com/ (R2023b or newer)." >&2
  exit 1
fi

export WEBOTS_HOME="${WEBOTS_HOME:-/usr/local/webots}"
# The controller imports nano/, laptop/ and shared/ from the repo, and needs the
# Webots controller bindings on the same path.
export PYTHONPATH="$REPO:$WEBOTS_HOME/lib/controller/python${PYTHONPATH:+:$PYTHONPATH}"
export LD_LIBRARY_PATH="$WEBOTS_HOME/lib/controller${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
# Webots picks the interpreter for a controller from the [python] COMMAND in the
# controller's runtime.ini, not from the environment. The controller needs
# numpy, opencv and pydantic, so point it at the repo venv when one exists;
# otherwise leave Webots to its default python3 and let it say what is missing.
RUNTIME_INI="$REPO/webots/controllers/episodic_robot/runtime.ini"
if [ -x "$REPO/.venv/bin/python" ]; then
  cat > "$RUNTIME_INI" <<INI
# Generated by scripts/run_webots_demo.sh - points Webots at the repo venv.
[python]
COMMAND = $REPO/.venv/bin/python
INI
else
  for module in numpy cv2 pydantic; do
    python3 -c "import $module" 2>/dev/null || {
      echo "warning: python3 cannot import '$module'; the controller will fail." >&2
      echo "         create the venv first:  python3 -m venv .venv && .venv/bin/pip install -r requirements-laptop.txt -r requirements-nano.txt" >&2
    }
  done
fi
if [ -n "${CONTROLLER_ARGS+x}" ] && [ ${#CONTROLLER_ARGS[@]} -gt 0 ]; then
  # Webots has no clean way to pass argv to a controller from the CLI, so the
  # controller also reads these from the environment.
  for ((i = 0; i < ${#CONTROLLER_ARGS[@]}; i++)); do
    case "${CONTROLLER_ARGS[$i]}" in
      --detector) export EPISODIC_DETECTOR="${CONTROLLER_ARGS[$((i + 1))]}" ;;
      --fog-url)  export EPISODIC_FOG_URL="${CONTROLLER_ARGS[$((i + 1))]}" ;;
    esac
  done
fi

if [ "$HEADLESS" -eq 1 ]; then
  command -v xvfb-run >/dev/null 2>&1 || { echo "xvfb-run not found (apt install xvfb)" >&2; exit 1; }
  # llvmpipe: Webots warns about software rendering, which is expected here.
  export LIBGL_ALWAYS_SOFTWARE=1 LC_ALL=C.UTF-8
  : "${USER:=webots}"; export USER

  if [ -n "$RECORD" ]; then
    SIZE="${WEBOTS_RECORD_SIZE:-1280x800}"
    echo "Recording to $RECORD (${SIZE}) ..."
    xvfb-run -a -s "-screen 0 ${SIZE}x24" bash -c "
      webots --batch --mode=fast --stdout --stderr '$WORLD' &
      WEBOTS_PID=\$!
      ffmpeg -nostdin -loglevel error -y -f x11grab -video_size '$SIZE' -framerate 20 \
             -i \"\$DISPLAY\" -pix_fmt yuv420p -crf 26 '$RECORD' &
      FFMPEG_PID=\$!
      wait \$WEBOTS_PID
      sleep 1; kill -INT \$FFMPEG_PID 2>/dev/null || true
      wait \$FFMPEG_PID 2>/dev/null || true
    "
    echo "Wrote $RECORD"
  else
    xvfb-run -a -s "-screen 0 1280x800x24" \
      webots --batch --mode=fast --no-rendering --stdout --stderr "$WORLD"
  fi
else
  webots "$WORLD"
fi

SUMMARY="$REPO/webots/controllers/episodic_robot/run_summary.json"
[ -f "$SUMMARY" ] && { echo "--- run summary ---"; cat "$SUMMARY"; }
